### ISSUE TITLE
More "Classic" Save / Restore

### ISSUE THREAD

**Issue by phf** [kensanata/gridmapper#1]
It's sexy that you download your map with a fully functional application. However that also traps your previous designs in whatever version of gridmapper you used back then. I have a neato dungeon stuck in an earlier version that cannot encode the dungeon into a URL, so now I am sort of stuck with that forever. I tried manually copy/pasting things into a newer version but I apparently don't have enough JS juice in my brain to succeed. So what struck me was this: A more "classic" save/restore (maybe via JSON?) could fix my problem as long as the code to "restore" was sufficiently backwards-compatible.

**Comment by kensanata** [comment]
The following procedure should work:

1. click on *Prepare Link* and click on the *Link* this creates – save it somewhere
2. this URL should now contain a little script to recreate the current state (see example below)
3. now replace the file with a new copy of Gridmapper
4. reload the URL you saved – this should recreate the current state

Example of such a URL: ```file:///Users/alex/Source/gridmapper/gridmapper.svg?%0A%20w.dfwwfwwfw%0A%20wftfw.wfwwfww.dddfw%0A%20wfffwnnnn%20nn%20wfwwfwwfw%0A%20ww%20ww%20w.dfffwfn%20nnn%20w%0A%20%20%20ww%20ww%20ww%20wfnnnn%20fd%0A%20%20%20%20%20%20ww%20ww%20ww```

Everything after the questionmark is a script:

1. ```%0A``` is Enter
2. ```%20``` is Space
3. ```w``` is wall (to the west)
4. ```.``` is a micro-pause
5. ```d``` is a door (to the north, because there's already a wall to the west)
6. ```f``` is floor
7. etc.

You can take this URL fragment and recreate your map elsewhere, too! To take the example above:

```https://campaignwiki.org/gridmapper.svg?%0A%20w.dfwwfwwfw%0A%20wftfw.wfwwfww.dddfw%0A%20wfffwnnnn%20nn%20wfwwfwwfw%0A%20ww%20ww%20w.dfffwfn%20nnn%20w%0A%20%20%20ww%20ww%20ww%20wfnnnn%20fd%0A%20%20%20%20%20%20ww%20ww%20ww```
